openapi: 3.0.0

info:
  title: Sentinel Access Review API
  description: >
    Retrieves current role assignments, role definitions, and directory role or group
    memberships from Microsoft Graph for use by the Sentinel Access Review Agent.
  version: "v1"

servers:
  - url: https://graph.microsoft.com/v1.0

paths:
  /roleManagement/directory/roleAssignments:
    get:
      operationId: GetDirectoryRoleAssignments
      summary: Get current directory role assignments
      description: >
        Returns all directory role assignments from Microsoft Entra ID, including
        principal, role definition, and scope information.
      responses:
        "200":
          description: Successful request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoleAssignmentsResponse"
        "401":
          description: Unauthorized – invalid or missing token
        "403":
          description: Forbidden – insufficient permissions

  /roleManagement/directory/roleDefinitions:
    get:
      operationId: GetDirectoryRoleDefinitions
      summary: Get directory role definitions
      description: >
        Retrieves the list of all available role definitions in Microsoft Entra ID.
      responses:
        "200":
          description: Successful request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoleDefinitionsResponse"
        "401":
          description: Unauthorized – invalid or missing token
        "403":
          description: Forbidden – insufficient permissions

  /users/{userId}/memberOf:
    get:
      operationId: GetUserMemberships
      summary: Get a user’s group or directory-role memberships
      description: >
        Retrieves groups or directory roles that the specified user belongs to.
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: The user’s object ID or UPN.
      responses:
        "200":
          description: Successful request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserMembershipsResponse"
        "401":
          description: Unauthorized – invalid or missing token
        "403":
          description: Forbidden – insufficient permissions

components:
  securitySchemes:
    AAD:
      type: oauth2
      description: Microsoft Entra ID OAuth 2.0 Client Credentials Flow
      flows:
        clientCredentials:
          tokenUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token
          scopes:
            https://graph.microsoft.com/.default: Access Microsoft Graph resources

  schemas:
    RoleAssignmentsResponse:
      type: object
      properties:
        value:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: Role assignment ID.
              principalId:
                type: string
                description: ID of the assigned principal (user, group, or service principal).
              principalType:
                type: string
                description: Type of the principal.
              roleDefinitionId:
                type: string
                description: Linked role definition ID.
              directoryScopeId:
                type: string
                description: Directory or resource scope.
              createdDateTime:
                type: string
                format: date-time
                description: Assignment creation timestamp.

    RoleDefinitionsResponse:
      type: object
      properties:
        value:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: Role definition ID.
              displayName:
                type: string
                description: Role display name.
              description:
                type: string
                description: Role description.
              isBuiltIn:
                type: boolean
                description: Indicates whether the role is built-in.
              rolePermissions:
                type: array
                items:
                  type: object
                  properties:
                    allowedResourceActions:
                      type: array
                      items:
                        type: string
                        description: Allowed resource actions for this role.

    UserMembershipsResponse:
      type: object
      properties:
        value:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: Group or directory role ID.
              displayName:
                type: string
                description: Name of the group or directory role.
              type:
                type: string
                description: Type of membership (Group or DirectoryRole).

security:
  - AAD: [ https://graph.microsoft.com/.default ]
